### ISSUE TITLE
dynamic number of elements per resolution

### ISSUE THREAD

**Issue by taleteller** [contao-bootstrap/grid-editor#9]
This issue is related to #8 

At the moment the grid-editor is handling grids as they where tables. When creating one you specify the number of columns, and assign widths to resolutions. This works fine until you columns get layout control or visibility properties. Key to understanding is that there is no limit to 12 columns per row, just no column can be wider than 12/12. 

Lets assume we make a responsive thumbnail page, with plenty of photos. At high resolution we get 4 images in a row, therefore we set 4 columns and declare `col-lg-3` in the editor. At medium resolution we can get 3 thumbs each row, therefore we set `col-md-4` here, for small ones `col-sm-6`, for tiny `col-xs-12`. 

The first thing you notice: 3 columns a row, dont match to 4 being declared. You would end up with a single 4/12 column every 2nd row, when understanding them like a table. Leaving this behind, you simply add all columns to one single "row", until your done. Like this:
```
<div class="row">
  <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">Content</div>
  <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">Content</div>
  <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">Content</div>
  <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">Content</div>
  <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">Content</div>
  <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">Content</div>
  <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">Content</div>
  <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">Content</div>
</div>
```
By ignoring the number of columns each row, it became way more responsible already. Instead of seeing the declarations in each resolution as a set, we should see them like a repeating loop. Since all columns in this example are equal wide, it would be enough to declare one column, in each resolution. 

This leads us to the problem I described in issue #8. Content of `<div>`s are rarely equally tall. Therefore you already can get a jumbled layout with simple responsible reordering, but by leaving the row tags for a while, it even gets worse. We need 'clearfixes', lets assume the grid-editor allows us to set them anywhere we need. Our code now looks like this: 

```
<div class="row">
  <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">Content</div>
  <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">Content</div>
  <div class="clearfix visible-sm-block"></div>
  <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">Content</div>
  <div class="clearfix visible-md-block"></div>
  <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">Content</div>
  <div class="clearfix visible-lg-block"></div>
  <div class="clearfix visible-sm-block"></div>
  <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">Content</div>
  <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">Content</div>
  <div class="clearfix visible-md-block"></div>
  <div class="clearfix visible-sm-block"></div>
  <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">Content</div>
  <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">Content</div>
  <div class="clearfix visible-lg-block"></div>
  <div class="clearfix visible-sm-block"></div>
</div>
```
Looks complicated, but isnt. We force a clearfix, every 4 elements on large, every 3 on medium, every 2 on small and never on tiny because its not needed. 

Now, how would we config that within the grid editor? Lets got with 4 columns on the top. For large resolution we set each of them with a width of 3, and force a clearfix on the last one. For small we would only need two, but we got four. Lets set all of them width 6 and force clearfix on the 2nd and last. Tiny, only one is required, but got 4 four as well. Set them 12, clearfix can be ignored. 

Now ... medium gives us a problem! Three is no integer fraction of four! We could set them a width of 4, but where to place the clearfixes? The third element wont work, because it would shift one in every loop. 

In our example, we would need to declare `2*3*4 = 12` columns for each resolution, to handle clearfixes of all its fractions. But thats only a solution assuming the set is simple, nothing gets shifted, column visibility is not a future feature and nobody sets anything but 12 columns in the config. 

That leads us back to the begin of this epic ;-) explanation: Each resolution should have its own number of columns, allowing adding and removing them as required. There is no fixed number of elements per row, since its not a table. Might be this interferes badly with the integration of present columnsets in contao.

**Comment by dmolineus** [comment]
Thanks for your epic story. :)

> Key to understanding is that there is no limit to 12 columns per row, just no column can be wider than 12/12.

I got your point. Most of what you explained is already possible with the defined grids of the grid editor. It's possible to create 3 columns with the width of (9-3-12). Which would create 2 rows.

So you have to understand the selected column size as slots where content can be inserted rather when grid columns (I know, they are limited to the grid size at the moment).

> Instead of seeing the declarations in each resolution as a set, we should see them like a repeating loop.

I think I got your implicit assumption now. You are thinking about iterating for each size over the defined grid columns instead of iterating over the chosen slot size. When it makes sense to add `+/-` buttons.

Your way would make it possible to create grids like `sm: 4-4-4, xs 4-1`, where the third column gets the size `xs-4`.

Theoretically I **do agree** with you that the grid can be used like this. What are the usecases for it and how can it be integrated without loosing any usability for editors.
 - You make an example of image galleries. I can imagine that it would fit there pretty well.
 - Do you manage your content on a page like this (in an infinite set of columns rather than a row like layout)?
 - Are you managing the content for your own or have editors access to it?

Using different number of grid columns for different sizes would break the current implentation and the usage of Subcolumns which is compromise for providing grids for editors for me (Not happy with it, would prefer a node concept as Typo3 NEOS has. But it's a Contao limitation so far).

It could be solved by providing different grid types as `fixed` and `flexible` where fixed would be the way it currently is. Flexible what you proposed. But changing the iterating process which is done by the [Walker](https://github.com/contao-bootstrap/grid-editor/blob/master/src/Walker.php) so far would definitly break backwards compatibility. So it's something for Version 2.0. 

If I ever ever release a version 2 when it would support Bootstrap 4. Rumors says it'll released this year.

If you have other suggestions how to integrate it without breaking everything let me know. Feel free to provide pull requests as well.

**Comment by taleteller** [comment]
Of course I agree this is not a critical issue, way lesser than #8, I also agree it's something that can be postponed to a future version because of the interference with the integration. In my opionion this points out a difference in the approach of bootstrap grids and contao columnsets. They got a intersection but are not the same. Thats something to be considered on the roadmap, because nobody wants to find issues with the foundation while building the upper floors ;-)

Acually i came across these things while i was layouting content for a site in progress. A Thumbnail page is just one example, theres others like cataloges, personal profile overviews etc. Pages with manual layout, not big enough to justify coding for automation. For my case, i will solve it with inline html, giving the editor a hint not to touch when possible. 

However Bootstrap grids are way more than just a way to get two columns somewhere in the middle of a page, and i have seen enough of your code to know you like to implement them the right way. ;-)

**Comment by dmolineus** [comment]
The grid insert tag has an infinite option now. So you can create endless columnsets. The only limitation is now that you have to define the whole pattern of columns.
